# NumPy

In [1]:
import numpy as np

In [2]:
L1 = [1,2,3,4,5,6,7,8]# Crear una lista

In [3]:
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x2 = np.array(L1, dtype='float32')
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_, float16, float32, float64 (+/-999.9999999e99999)
- complex_, complex64, complex128 (a+bi, a,b $\in$ float_) 

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3,12,dtype=np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [10]:
np.linspace(1., 7., 12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
x.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
x.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
x = np.array([[1,2,3,4], [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [22]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
np.resize(x, (5, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios
1. Crear un array de datos con valores entre 5 y 120.
2. Crear una matriz 4x4 con los valores desde 0 hasta 15.
3. Crear la identidad 7x7
4. Crear un array de 20 elementos y transformarlos en una matrix 5x4
5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme

## Propiedades de los arrays

In [27]:
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
x.ndim

2

In [30]:
x.shape

(3, 4)

In [31]:
x.size

12

In [32]:
x.dtype

dtype('int64')

In [33]:
x.itemsize

8

In [34]:
x.data

In [35]:
x[2]

array([ 8,  9, 10, 11])

In [36]:
x[2,1]

9

In [37]:
x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
x[1:3, 0:2]

array([[3, 4],
       [6, 7]])

In [39]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
y[3:8]

array([3, 4, 5, 6, 7])

In [41]:
y[1:7:2]

array([1, 3, 5])

In [42]:
z = np.arange(10, 6, -1)
z

array([10,  9,  8,  7])

In [43]:
y[z]

array([10,  9,  8,  7])

In [44]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [47]:
cond = (x < 25)
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [48]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [50]:
x[13:16] = [6,9,12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
x.dtype

dtype('int64')

In [52]:
x[5] = 3.1415
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
x[8] = 1.2j 

TypeError: can't convert complex to int

## Copias y vistas de arrays

In [54]:
x = np.arange(10)

In [55]:
y = x

In [56]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
z is x

False

In [60]:
y is x

True

In [61]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
t.shape = (5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [64]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
s = x[0:2, 1:3]
s

array([[1, 2],
       [6, 7]])

In [66]:
s[:] = 5
s

array([[5, 5],
       [5, 5]])

In [67]:
x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [68]:
y

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [69]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Funciones Univeresales (ufunc)
- Unarias: sqrt, sin, cos, **2
- Binarias: maximum, minimum 

In [70]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [73]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [74]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [75]:
alpha = np.linspace(0,2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [76]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [77]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [78]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [79]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [80]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [81]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [82]:
np.power(x, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [83]:
np.log(x)

/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [84]:
np.log2(x)

/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [85]:
np.log10(x)

/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

$$\sum_{i=1}^n x_i$$

In [86]:
np.sum(x)

45

In [87]:
np.nansum(x)

45

In [88]:
np.prod(x)

0

In [89]:
np.mean(x)

4.5

In [90]:
np.median(x)

4.5

In [91]:
np.min(x)

0

In [92]:
np.max(x)

9

In [93]:
np.std(x)

2.8722813232690143

In [94]:
np.var(x)

8.25

In [95]:
np.argmin(x)

0

In [96]:
np.argmax(x)

9

In [99]:
np.percentile(x, q=0.95)

0.08549999999999999

In [105]:
 y = np.array([True, True, True, True])

In [106]:
np.any(y)

True

In [107]:
np.all(y)

True

In [116]:
np.random.seed(2019)
z = np.random.random((3,5))
z

array([[0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907],
       [0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ],
       [0.45244662, 0.26707032, 0.16286487, 0.8892147 , 0.14847623]])

In [117]:
z.sum()

8.550690063213514

In [118]:
z.sum(axis=0)

array([1.65510085, 1.3623491 , 1.69004099, 2.40847402, 1.43472509])

In [119]:
z.sum(axis=1)

array([3.43890915, 3.19170818, 1.92007274])